package ch.uzh.ifi.hase.soprafs26.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpStatus;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.web.server.ResponseStatusException;

import ch.uzh.ifi.hase.soprafs26.constant.UserStatus;
import ch.uzh.ifi.hase.soprafs26.entity.User;
import ch.uzh.ifi.hase.soprafs26.repository.UserRepository;

import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@WebAppConfiguration
@SpringBootTest(properties = "HUGGINGFACE_API_TOKEN=mock-key")
public class UserServiceIntegrationTest {

    @Qualifier("userRepository")
    @Autowired
    private UserRepository userRepository;

    @Autowired
    private UserService userService;

    @BeforeEach
    public void setup() {
        userRepository.deleteAll();
    }

    // Helper to build a valid, unique user without persisting it
    private User buildUser() {
        User user = new User();
        user.setUsername("user_" + UUID.randomUUID());
        user.setPassword("password");
        user.setName("name_" + UUID.randomUUID());
        user.setEmail(UUID.randomUUID() + "@test.com");
        user.setLanguage("EN");
        user.setManager(false);
        return user;
    }

    @Test
    public void createUser_validInputs_success() {
        assertNull(userRepository.findByUsername("testUsername"));

        User testUser = new User();
        testUser.setUsername("testUsername");
        testUser.setPassword("testPassword");
        testUser.setName("testName");
        testUser.setEmail("email@test.com");
        testUser.setLanguage("German");
        testUser.setManager(false);

        User createdUser = userService.createUser(testUser);

        assertEquals(testUser.getId(), createdUser.getId());
        assertEquals("testUsername", createdUser.getUsername());
        assertNotNull(createdUser.getToken());
        assertEquals(UserStatus.ONLINE, createdUser.getStatus());
    }

    @Test
    public void createUser_duplicateUsername_throwsException() {
        User first = buildUser();
        first.setUsername("duplicateUser");
        userService.createUser(first);

        User second = new User();
        second.setUsername("duplicateUser");
        second.setPassword("otherPassword");

        assertThrows(ResponseStatusException.class, () -> userService.createUser(second));
    }

    @Test
    public void createUser_tokenIsAutoGenerated_andUnique() {
        User u1 = userService.createUser(buildUser());
        User u2 = userService.createUser(buildUser());

        assertNotNull(u1.getToken());
        assertNotNull(u2.getToken());
        assertNotEquals(u1.getToken(), u2.getToken());
    }

    @Test
    public void getUsers_multipleUsers_returnsAll() {
        userService.createUser(buildUser());
        userService.createUser(buildUser());

        List<User> users = userService.getUsers();

        assertEquals(2, users.size());
    }

    @Test
    public void getUsers_emptyRepository_returnsEmptyList() {
        assertTrue(userService.getUsers().isEmpty());
    }

    @Test
    public void loginUser_validCredentials_setsOnline() {
        User registered = buildUser();
        registered.setPassword("secret");
        userService.createUser(registered);

        // Manually set OFFLINE to verify loginUser flips it back
        registered.setStatus(UserStatus.OFFLINE);
        userRepository.save(registered);

        User credentials = new User();
        credentials.setUsername(registered.getUsername());
        credentials.setPassword("secret");

        User loggedIn = userService.loginUser(credentials);

        assertEquals(UserStatus.ONLINE, loggedIn.getStatus());
    }

    @Test
    public void loginUser_wrongPassword_throwsUnauthorized() {
        User registered = buildUser();
        registered.setPassword("correctPassword");
        userService.createUser(registered);

        User attempt = new User();
        attempt.setUsername(registered.getUsername());
        attempt.setPassword("wrongPassword");

        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
                () -> userService.loginUser(attempt));
        assertEquals(HttpStatus.UNAUTHORIZED, exception.getStatusCode());
    }

    @Test
    public void loginUser_unknownUsername_throwsNotFound() {
        User attempt = new User();
        attempt.setUsername("nobody");
        attempt.setPassword("anything");

        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
                () -> userService.loginUser(attempt));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
    }

    @Test
    public void getUserById_existingId_returnsUser() {
        User saved = userService.createUser(buildUser());

        User found = userService.getUserById(saved.getId());

        assertEquals(saved.getId(), found.getId());
        assertEquals(saved.getUsername(), found.getUsername());
    }

    @Test
    public void getUserById_nonExistingId_throwsNotFound() {
        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
                () -> userService.getUserById(9999L));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
    }

    @Test
    public void updateUser_validUsername_isPersisted() {
        User saved = userService.createUser(buildUser());

        User updates = new User();
        updates.setUsername("brandNewUsername");

        userService.updateUser(saved.getId(), updates);

        User reloaded = userRepository.findById(saved.getId()).orElseThrow();
        assertEquals("brandNewUsername", reloaded.getUsername());
    }

    @Test
    public void updateUser_validPassword_isPersisted() {
        User saved = userService.createUser(buildUser());

        User updates = new User();
        updates.setPassword("newSecurePassword");

        userService.updateUser(saved.getId(), updates);

        User reloaded = userRepository.findById(saved.getId()).orElseThrow();
        assertEquals("newSecurePassword", reloaded.getPassword());
    }

    @Test
    public void updateUser_validLanguage_isPersisted() {
        User saved = userService.createUser(buildUser());

        User updates = new User();
        updates.setLanguage("DE");

        userService.updateUser(saved.getId(), updates);

        User reloaded = userRepository.findById(saved.getId()).orElseThrow();
        assertEquals("DE", reloaded.getLanguage());
    }

    @Test
    public void updateUser_nonExistingId_throwsNotFound() {
        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
                () -> userService.updateUser(9999L, new User()));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
    }

    @Test
    public void updateUserLanguage_validToken_isPersisted() {
        User saved = userService.createUser(buildUser());

        User updated = userService.updateUserLanguage(saved.getToken(), "FR");

        assertEquals("FR", updated.getLanguage());
        assertEquals("FR", userRepository.findById(saved.getId()).orElseThrow().getLanguage());
    }

    @Test
    public void updateUserLanguage_invalidToken_throwsNotFound() {
        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
                () -> userService.updateUserLanguage("invalid-token", "DE"));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
    }

    @Test
    public void verifyToken_validToken_doesNotThrow() {
        User saved = userService.createUser(buildUser());

        assertDoesNotThrow(() -> userService.verifyToken(saved.getToken()));
    }

    @Test
    public void verifyToken_invalidToken_throwsUnauthorized() {
        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
                () -> userService.verifyToken("not-a-real-token"));
        assertEquals(HttpStatus.UNAUTHORIZED, exception.getStatusCode());
    }

    @Test
    public void verifyToken_nullToken_throwsUnauthorized() {
        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
                () -> userService.verifyToken(null));
        assertEquals(HttpStatus.UNAUTHORIZED, exception.getStatusCode());
    }

    @Test
    public void logoutById_validId_setsOffline() {
        User saved = userService.createUser(buildUser());
        assertEquals(UserStatus.ONLINE, saved.getStatus());

        userService.logoutById(saved.getId());

        User reloaded = userRepository.findById(saved.getId()).orElseThrow();
        assertEquals(UserStatus.OFFLINE, reloaded.getStatus());
    }

    @Test
    public void logoutById_nonExistingId_throwsNotFound() {
        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
                () -> userService.logoutById(9999L));
        assertEquals(HttpStatus.NOT_FOUND, exception.getStatusCode());
    }

    @Test
    public void setUserStatus_validToken_setsOffline() {
        User saved = userService.createUser(buildUser());

        userService.setUserStatus(saved.getToken());

        User reloaded = userRepository.findById(saved.getId()).orElseThrow();
        assertEquals(UserStatus.OFFLINE, reloaded.getStatus());
    }

    @Test
    public void setUserStatus_unknownToken_doesNothing() {
        assertDoesNotThrow(() -> userService.setUserStatus("ghost-token"));
    }
}